import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import announcementsRouter from "./announcements";
import schedulesRouter from "./schedules";
import inventoryRouter from "./inventory";
import deadlinesRouter from "./deadlines";
import complaintsRouter from "./complaints";
import issuesRouter from "./issues";
import templatesRouter from "./templates";
import dashboardRouter from "./dashboard";
import kasRouter from "./kas";
import prokerFundsRouter from "./proker-funds";
import permissionsRouter from "./permissions";
import notulensiRouter from "./notulensi";
import membersRouter from "./members";
import storageRouter from "./storage";
import conditionsRouter from "./conditions";
import attendanceRouter from "./attendance";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(announcementsRouter);
router.use(schedulesRouter);
router.use(inventoryRouter);
router.use(deadlinesRouter);
router.use(complaintsRouter);
router.use(issuesRouter);
router.use(templatesRouter);
router.use(dashboardRouter);
router.use(kasRouter);
router.use(prokerFundsRouter);
router.use(permissionsRouter);
router.use(notulensiRouter);
router.use(membersRouter);
router.use(storageRouter);
router.use(conditionsRouter);
router.use(attendanceRouter);

export default router;
